# Validating the YAML file:
# https://docs.travis-ci.com/user/travis-lint/

# https://docs.travis-ci.com/user/ci-environment/
sudo: false
language: java

# https://docs.travis-ci.com/user/languages/java/
jdk:
  - oraclejdk8
  - oraclejdk7

# https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

# https://docs.travis-ci.com/user/customizing-the-build
install: mvn -B -V install -DskipTests=true -Dinvoker.skip=true -Dmaven.javadoc.skip=true
script: mvn clean verify site
after_failure: cat /home/travis/build/stephanenicolas/javassist-maven-plugin/src/it/resources/project1/build.log

