language: java
jdk: openjdk6

# https://blog.travis-ci.com/2017-05-04-precise-image-updates
sudo: required

install: mvn -DskipTests=true -Dinvoker.skip -B -V install
script: mvn clean install 

after_failure: cat /home/travis/build/stephanenicolas/javassist-maven-plugin/src/it/resources/project1/build.log


